name: Check JSON Schemas
on: [push]

jobs:
  Check-JSON-Schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate hooks
        uses: cardinalby/schema-validator-action@v3
        with:
          schema: ./schemas/hooks.json
          file: ./hooks/index.json
